version: '3'
services:
  # Django
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    hostname: app
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    expose:
      - "8000"
    restart: on-failure